export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_BY_MONTH = "GET_HISTORY_BY_MONTH";
export const GET_HISTORY_BY_YEAR = "GET_HISTORY_BY_YEAR";
export const GET_HISTORY_YEARS = "GET_HISTORY_BY_YEAR";
export const GET_HISTORY_MONTHS = "GET_HISTORY_BY_YEAR";
